const fs = require('fs');
const path = require('path');

const AppError = require('../../core/errors/AppError');
const { runtimeConfig } = require('../../config/runtime');
const { sanitizeText } = require('../../utils/validators');

const VERSION_TOKEN_PATTERN = /^[0-9A-Za-z._-]+$/;
const SHA256_PATTERN = /^[a-f0-9]{64}$/;

const resolveAppUpdateConfigPath = () =>
  path.resolve(process.env.APP_UPDATE_CONFIG_PATH || path.join(process.cwd(), 'app-update.json'));

const resolveApkDirectoryPath = () =>
  path.resolve(process.env.APP_UPDATE_APK_DIR || path.join(process.cwd(), 'apk'));

const sanitizeVersionToken = (value, fallback = '') => {
  const normalized = sanitizeText(value, 80).replace(/^v/i, '');
  if (!normalized) {
    return fallback;
  }
  return VERSION_TOKEN_PATTERN.test(normalized) ? normalized : fallback;
};

const sanitizeApkFileName = (value) => {
  const normalized = sanitizeText(value, 200).replace(/[\\/]/g, '').trim();
  if (!normalized || !normalized.toLowerCase().endsWith('.apk')) {
    return '';
  }
  return normalized;
};

const normalizeAbsoluteHttpUrl = (value) => {
  const raw = String(value || '').trim();
  if (!raw) {
    return '';
  }
  try {
    const parsed = new URL(raw);
    if (!['http:', 'https:'].includes(parsed.protocol)) {
      return '';
    }
    return parsed.toString();
  } catch (_) {
    return '';
  }
};

const normalizePublicBaseUrl = (value) => {
  const absolute = normalizeAbsoluteHttpUrl(value);
  if (!absolute) {
    return '';
  }
  const parsed = new URL(absolute);
  return `${parsed.protocol}//${parsed.host}`;
};

const looksLikeHostPath = (value) =>
  /^[A-Za-z0-9.-]+\.[A-Za-z]{2,}(:\d+)?($|\/)/.test(String(value || '').trim());

const resolvePublicApiBaseUrl = (req) => {
  const configured =
    normalizePublicBaseUrl(process.env.APP_API_BASE_URL) ||
    normalizePublicBaseUrl(runtimeConfig.urls.apiPublicBaseUrl);
  if (configured) {
    return configured;
  }
  const protocol = req.protocol === 'https' ? 'https' : 'http';
  return `${protocol}://${req.get('host')}`;
};

const resolveApkUrl = ({ req, config }) => {
  const defaultPath = `/api/v1/app/apk/${encodeURIComponent(config.latestVersion)}`;
  const explicit = String(config.explicitApkUrl || '').trim();
  if (!explicit) {
    return `${resolvePublicApiBaseUrl(req)}${defaultPath}`;
  }

  const absoluteExplicit = normalizeAbsoluteHttpUrl(explicit);
  if (absoluteExplicit) {
    return absoluteExplicit;
  }

  if (explicit.startsWith('//')) {
    const scheme = req.protocol === 'https' ? 'https' : 'http';
    return `${scheme}:${explicit}`;
  }

  if (looksLikeHostPath(explicit)) {
    const base = resolvePublicApiBaseUrl(req);
    const scheme = base.startsWith('https://') ? 'https' : 'http';
    return `${scheme}://${explicit}`;
  }

  const relativePath = explicit.startsWith('/') ? explicit : `/${explicit}`;
  return `${resolvePublicApiBaseUrl(req)}${relativePath}`;
};

const readConfigPayload = () => {
  const configPath = resolveAppUpdateConfigPath();
  if (!fs.existsSync(configPath)) {
    throw new AppError('App update config not found', 503, {
      code: 'APP_UPDATE_CONFIG_NOT_FOUND',
      details: {
        configPath,
      },
    });
  }

  let parsed = null;
  try {
    // Accept UTF-8 BOM-prefixed files generated by some Windows editors/scripts.
    const rawConfig = fs.readFileSync(configPath, 'utf8').replace(/^\uFEFF/, '');
    parsed = JSON.parse(rawConfig);
  } catch (_) {
    throw new AppError('App update config contains invalid JSON', 500, {
      code: 'APP_UPDATE_CONFIG_INVALID',
      details: {
        configPath,
      },
    });
  }

  const latestVersion = sanitizeVersionToken(parsed.latestVersion);
  if (!latestVersion) {
    throw new AppError('latestVersion is required in app-update.json', 500, {
      code: 'APP_UPDATE_LATEST_VERSION_REQUIRED',
      details: {
        configPath,
      },
    });
  }

  const minimumSupportedVersion =
    sanitizeVersionToken(parsed.minimumSupportedVersion, latestVersion) || latestVersion;
  const releaseNotes = sanitizeText(parsed.releaseNotes, 2_000);
  const sha256Raw = sanitizeText(parsed.sha256, 128).toLowerCase();
  const sha256 = SHA256_PATTERN.test(sha256Raw) ? sha256Raw : '';
  const apkFileName = sanitizeApkFileName(parsed.apkFileName) || `green_toilet_v${latestVersion}.apk`;
  const explicitApkUrl = String(parsed.apkUrl || '').trim();

  const stat = fs.statSync(configPath);

  return {
    latestVersion,
    minimumSupportedVersion,
    releaseNotes,
    sha256,
    apkFileName,
    explicitApkUrl,
    updatedAt: stat.mtime.toISOString(),
    configPath,
  };
};

const resolveCandidateApkNames = ({ requestedVersion, config }) => {
  const candidates = [];

  if (requestedVersion === config.latestVersion) {
    candidates.push(config.apkFileName);
  }

  candidates.push(`green_toilet_v${requestedVersion}.apk`);
  candidates.push(`green_toilet-${requestedVersion}.apk`);
  candidates.push(`app_v${requestedVersion}.apk`);
  candidates.push(`${requestedVersion}.apk`);

  return Array.from(new Set(candidates.map((name) => sanitizeApkFileName(name)).filter(Boolean)));
};

const resolveVersionedApkPath = ({ apkDir, fileName }) => {
  const absoluteDir = path.resolve(apkDir);
  const absoluteFile = path.resolve(absoluteDir, fileName);

  if (!absoluteFile.startsWith(`${absoluteDir}${path.sep}`)) {
    throw new AppError('Invalid APK file path resolution', 400, {
      code: 'APP_UPDATE_INVALID_APK_PATH',
    });
  }

  return absoluteFile;
};

const getAppUpdateMetadata = (req) => {
  const config = readConfigPayload();
  const apkUrl = resolveApkUrl({ req, config });

  return {
    latestVersion: config.latestVersion,
    minimumSupportedVersion: config.minimumSupportedVersion,
    apkUrl,
    apkFileName: config.apkFileName,
    releaseNotes: config.releaseNotes,
    sha256: config.sha256,
    updatedAt: config.updatedAt,
  };
};

const resolveApkDownload = (req) => {
  const requestedVersion = sanitizeVersionToken(req.params.version);
  if (!requestedVersion) {
    throw new AppError('Invalid app version', 400, {
      code: 'APP_UPDATE_INVALID_VERSION',
    });
  }

  const config = readConfigPayload();
  const apkDir = resolveApkDirectoryPath();
  const candidates = resolveCandidateApkNames({ requestedVersion, config });

  let selected = null;
  for (const candidate of candidates) {
    const candidatePath = resolveVersionedApkPath({
      apkDir,
      fileName: candidate,
    });
    if (fs.existsSync(candidatePath)) {
      selected = {
        fileName: candidate,
        filePath: candidatePath,
      };
      break;
    }
  }

  if (!selected) {
    throw new AppError('APK not found for requested version', 404, {
      code: 'APP_UPDATE_APK_NOT_FOUND',
      details: {
        requestedVersion,
        apkDirectory: apkDir,
        searched: candidates,
      },
    });
  }

  return selected;
};

module.exports = {
  getAppUpdateMetadata,
  resolveApkDownload,
};
