const defaults = Object.freeze({
  app: {
    ingestRateLimitMax: 5000,
    sensorIngestRateLimitMax: 1200,
  },
  server: {
    headersTimeoutMs: 125_000,
    keepAliveTimeoutMs: 65_000,
    dbStartupMaxAttempts: 4,
    dbStartupRetryDelayMs: 2_000,
    autoRunMigrations: null,
    autoRunMigrationsStrict: null,
    autoBackfillToiletQrOnBoot: true,
    qrForceRegenerateOnBoot: false,
    analysisBootStrict: false,
    analysisWorkerEmbedded: true,
  },
  logging: {
    requestLoggingEnabled: true,
    requestLoggingVerbose: false,
    requestLoggingSlowMs: 1_200,
  },
  queue: {
    attempts: 3,
    backoffMs: 1_000,
    removeOnComplete: 200,
    removeOnFail: 1_000,
    dlqRemoveOnComplete: 50,
    dlqRemoveOnFail: 500,
    workerConcurrency: 2,
    analysisWorkerConcurrency: 2,
    analysisQueueAttempts: 4,
    analysisQueueBackoffMs: 1_200,
    analysisQueueRemoveOnComplete: 200,
    analysisInlineTimeoutMs: 120_000,
    analysisInlineConcurrency: 2,
    analysisInlineQueueMax: 1_000,
    analysisDedupWindowMs: 120_000,
    analysisStaleWatchdogIntervalMs: 30_000,
    analysisProcessingStaleMs: 180_000,
    redisRequiredInProduction: false,
    redisLiveChannel: 'sanitation:live:events',
  },
  idempotency: {
    lockMs: 60_000,
    ttlMs: 86_400_000,
    responseMaxBytes: 256 * 1024,
  },
  live: {
    sseHeartbeatMs: 20_000,
    wsHeartbeatMs: 25_000,
  },
  analysis: {
    confidenceThreshold: 0.7,
    reviewConfidenceThreshold: 0.6,
    rejectConfidenceThreshold: 0.4,
    scoreSpreadGain: 1.16,
    alwaysScoreOnFailure: true,
    blurVarianceMin: 120,
    brightnessMin: 35,
    brightnessMax: 220,
    validationMaxDimension: 768,
    fraudSimilarityThreshold: 0.92,
    mediaMaxBytes: 12 * 1024 * 1024,
    mediaFetchTimeoutMs: 10_000,
    aiImageMaxRetries: 4,
    aiRetryBaseDelayMs: 3_000,
    jobLeaseMs: 180_000,
    improvementThreshold: 5,
  },
  imageSession: {
    reconcileIntervalMs: 45_000,
    reconcileBatchSize: 100,
    reconcileMaxAttempts: 5,
    staleMs: 90_000,
  },
  diagnostics: {
    analysisStaleMs: 180_000,
    imageSessionStaleMs: 900_000,
  },
  media: {
    s3ObjectMaxBufferBytes: 12 * 1024 * 1024,
    uploadDiagnosticsLogsEnabled: false,
    tempUploadSubdir: 'uploads/temp',
    tempFileJanitorIntervalMs: 30 * 60 * 1000,
    tempFileMaxAgeMs: 6 * 60 * 60 * 1000,
    tempFileJanitorMaxDeletePerRun: 500,
  },
  alerts: {
    // BLE wand environmental thresholds. Physically-meaningful metrics
    // (temperature °C, humidity %) ship with sane defaults. The PPM gas
    // channel (TGS sensor) has no finally-confirmed calibration yet, so its
    // thresholds default to null (disabled) — operators must set calibrated
    // values before any PPM alert fires. `null` => metric disabled.
    sensor: {
      temperature: { highWarningC: 35, highCriticalC: 40, lowWarningC: null, lowCriticalC: null },
      humidity: { highWarningPct: 80, highCriticalPct: 90, lowWarningPct: 15, lowCriticalPct: 8 },
      ppm: { warning: null, critical: null },
      battery: { lowWarningPct: 20, lowCriticalPct: 10 },
      offline: { warningMinutes: 30, criticalMinutes: 180 },
    },
  },
  automation: {
    criticalComplaintValues: ['critical', 'emergency', 'very_bad', 'very bad'],
    repeatedComplaintWindowMinutes: 120,
    repeatedComplaintThreshold: 3,
    workerLocationFreshnessMinutes: 30,
    maxActiveTasksPerWorker: 3,
    lowMobileBatteryThreshold: 20,
    assignmentRadiusKm: 10,
    acceptReminderMinutes: 10,
    startReminderMinutes: 20,
    slaWarningMinutes: 15,
    reminderJobIntervalMs: 60_000,
    offlineEscalationMinutes: 45,
    mapPollingIntervalMs: 30_000,
    slaMinutesByPriority: {
      critical: 60,
      high: 120,
      medium: 240,
      low: 480,
    },
  },
});

module.exports = {
  defaults,
};
